### ISSUE TITLE
Download links to binaries

### ISSUE THREAD

**Issue by malwarenights** [hasherezade/pe_recovery_tools#1]
Hello Hasherezade,
thank you for sharing the tools - respect.

Please would you consider publishing the google download links in a form which can be used for direct download? 

Such as:

https://drive.google.com/uc?export=download&id=0Bzb5kQFOXkiSWkZWVkxWZTVRZnc     find_forwarders.exe

https://drive.google.com/uc?export=download&id=0Bzb5kQFOXkiScnotUWtyM0dyYlk     va_to_import.exe

https://drive.google.com/uc?export=download&id=0Bzb5kQFOXkiSc0J2Y0JXcGZuUFk     pe_unmapper.exe

https://drive.google.com/uc?export=download&id=0Bzb5kQFOXkiScUhoWDFHbi05TkE     imports_unerase.exe

Thank you
Mik

**Comment by hasherezade** [comment]
This is a good idea. I will do.

**Comment by malwarenights** [comment]
Thank you.
